# Generated by Django 5.1.4 on 2025-01-08 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_sign_language', models.BooleanField(default=False)),
                ('preferred_sign_language', models.CharField(blank=True, choices=[('ASL', 'American Sign Language'), ('BSL', 'British Sign Language'), ('AUSLAN', 'Australian Sign Language'), ('ISL', 'International Sign Language'), ('OTHER', 'Other Sign Language')], max_length=50, null=True)),
                ('needs_captions', models.BooleanField(default=False)),
                ('caption_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('other', 'Other')], default='en', max_length=50)),
                ('caption_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('visual_alerts', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('text_to_speech', models.BooleanField(default=False)),
                ('preferred_communication', models.CharField(choices=[('email', 'Email'), ('chat', 'Chat'), ('video', 'Video Call'), ('sign_language', 'Sign Language Video Call')], default='email', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accessibility Preference',
                'verbose_name_plural': 'Accessibility Preferences',
            },
        ),
    ]
