# Generated by Django 5.1.4 on 2025-01-09 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accessibilitypreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessibilityPreference',
        ),
    ]
